import { Article } from "@/types/article"
import { users } from "./users"

export const articles: Article[] = [
  {
    id: "1",
    title: "The Future of Web Development",
    slug: "future-of-web-development",
    excerpt: "Explore the latest trends and technologies shaping the web development landscape in 2025.",
    content: "Web development is evolving rapidly, with new frameworks, tools, and methodologies emerging every year...",
    date: "2025-01-01T10:00:00Z",
    coverImage: "https://example.com/images/future-web-dev.jpg",
    author: users[0],
  },
  {
    id: "2",
    title: "Mastering TypeScript",
    slug: "mastering-typescript",
    excerpt: "A comprehensive guide to becoming proficient in TypeScript.",
    content: "TypeScript has become a cornerstone of modern JavaScript development, offering static typing, interfaces, and more...",
    date: "2025-01-02T12:00:00Z",
    coverImage: "https://example.com/images/mastering-ts.jpg",
    author: users[1],
  },
  {
    id: "3",
    title: "Understanding React Server Components",
    slug: "react-server-components",
    excerpt: "Delve into the world of React Server Components and how they improve performance.",
    content: "React Server Components (RSC) provide a powerful way to offload rendering to the server...",
    date: "2025-01-03T09:30:00Z",
    coverImage: "https://example.com/images/react-server.jpg",
    author: users[2],
  },
  {
    id: "4",
    title: "Top 10 CSS Frameworks for 2025",
    slug: "top-css-frameworks-2025",
    excerpt: "Discover the most popular CSS frameworks developers are using this year.",
    content: "Choosing the right CSS framework can greatly accelerate your design workflow...",
    date: "2025-01-04T08:15:00Z",
    coverImage: "https://example.com/images/css-frameworks.jpg",
    author: users[3],
  },
  {
    id: "5",
    title: "A Beginner's Guide to Node.js",
    slug: "beginners-guide-nodejs",
    excerpt: "Learn the basics of Node.js and how to build your first server.",
    content: "Node.js is a powerful runtime that allows developers to run JavaScript on the server...",
    date: "2025-01-05T14:00:00Z",
    coverImage: "https://example.com/images/nodejs-guide.jpg",
    author: users[4],
  },
  {
    id: "6",
    title: "Building Scalable Microservices",
    slug: "scalable-microservices",
    excerpt: "A deep dive into designing and implementing scalable microservices architectures.",
    content: "Microservices have become a standard for building scalable and maintainable applications...",
    date: "2025-01-06T10:45:00Z",
    coverImage: "https://example.com/images/microservices.jpg",
    author: users[5],
  },
  {
    id: "7",
    title: "Introduction to AI in Software Development",
    slug: "ai-in-software-development",
    excerpt: "How artificial intelligence is reshaping software development practices.",
    content: "AI tools and technologies are making software development faster, more efficient, and smarter...",
    date: "2025-01-07T11:00:00Z",
    coverImage: "https://example.com/images/ai-software.jpg",
    author: users[6],
  },
  {
    id: "8",
    title: "Kubernetes for Beginners",
    slug: "kubernetes-for-beginners",
    excerpt: "An easy-to-follow guide to getting started with Kubernetes.",
    content: "Kubernetes is the de facto standard for container orchestration in modern DevOps workflows...",
    date: "2025-01-08T09:00:00Z",
    coverImage: "https://example.com/images/kubernetes.jpg",
    author: users[7],
  },
  {
    id: "9",
    title: "Why Accessibility Matters in Web Design",
    slug: "web-design-accessibility",
    excerpt: "Understanding the importance of accessibility in creating inclusive websites.",
    content: "Accessibility ensures that everyone, including people with disabilities, can use your website effectively...",
    date: "2025-01-09T13:00:00Z",
    coverImage: "https://example.com/images/accessibility.jpg",
    author: users[8],
  },
  {
    id: "10",
    title: "Optimizing Performance for Single Page Applications",
    slug: "performance-spa",
    excerpt: "Techniques to make your SPAs load faster and run smoother.",
    content: "Performance optimization is crucial for ensuring a great user experience in single page applications...",
    date: "2025-01-10T10:30:00Z",
    coverImage: "https://example.com/images/spa-performance.jpg",
    author: users[9],
  },
];

export const featuredArticle: Article = articles[0]
